In [1]:
import pandas as pd
import numpy as np

# Task1

In [4]:
i = int(input('Введите число: '))
numpy_array = np.arange(i - 1, -1, -1)
numpy_array

Введите число: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Task2

In [6]:
i = int(input('Введите число: '))
numpy_array = np.arange(i - 1, -1, -1)
diagonal_matrix = np.diag(numpy_array)
print(diagonal_matrix)
print(sum(np.diag(diagonal_matrix)))

Введите число: 10
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
45


# Task3

In [ ]:
df = pd.read('')

# Task4

In [41]:
df = pd.read_csv('power.csv')
df.head()

country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [42]:
df_filtered = df[(df['year']  >= 2005) & (df['year'] <= 2010) & (df['category'].isin(['4', '12', '21'])) 
                & (df['country'].isin(['Latvia', 'Estonia', 'Lithuania'])) & (df['quantity'] > 0)]
df_filtered.head()

country  year  quantity  category
10617    Estonia  2008       1.0         4
10620    Estonia  2005       1.0         4
11156  Lithuania  2008       1.0         4
11158  Lithuania  2006       1.0         4
11159  Lithuania  2005       1.0         4

In [43]:
sum_consumption = df_filtered['quantity'].sum()
print(sum_consumption)

240580.0


In [44]:
df_filtered['category'].unique()

array([ 4, 12, 21])

# Task 5

In [7]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
x = np.linalg.solve(a, b)
print(x)
print(np.allclose(np.dot(a, x), b))

[ 0.46666667  3.84444444 -5.55555556]
True
