In [1]:
import pandas as pd
import numpy as np

# Task1

In [4]:
i = int(input('Введите число: '))
numpy_array = np.arange(i - 1, -1, -1)
numpy_array

Введите число: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Task2

In [6]:
i = int(input('Введите число: '))
numpy_array = np.arange(i - 1, -1, -1)
diagonal_matrix = np.diag(numpy_array)
print(diagonal_matrix)
print(sum(np.diag(diagonal_matrix)))

Введите число: 10
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
45


# Task3

Способ получился довольно костыльным, потому что я не смог быстро понять, как работать с аутпутом группировки (там получается series а не dataframe). Наверняка есть более изящный способ, но с заданием я вроде бы справился. Надеюсь, что через какое-то время, глянув на этот код, я пойму, что это совсем жестко, и буду знать красивый метод))

In [92]:
df_movies = pd.read_csv('movies.csv')
#df_movies.head()

In [93]:
df_ratings = pd.read_csv('ratings.csv')
#df_ratings.head()

In [94]:
df_merged = pd.merge(df_movies, df_ratings, on='movieId')
df_merged.head()

movieId             title                                       genres  \
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
1        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
2        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
3        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
4        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   

   userId  rating   timestamp  
0       1     4.0   964982703  
1       5     4.0   847434962  
2       7     4.5  1106635946  
3      15     2.5  1510577970  
4      17     4.5  1305696483

Оставляем только оценки 5.0 и считаем количество таких оценок для каждого фильма

In [98]:
df_merged_5 = df_merged[(df_merged['rating'] == 5.0)].groupby(by=['title'])['rating'].count()
#df_merged_5.head()

Делаем из полученной группировки csv, которую потом откроем и отсортируем. Сходу не получилось, результат предыдущего шага сразу отсортировать не получилось

In [101]:
pd.DataFrame(df_merged_5).to_csv('check.csv', sep=',', encoding='utf-8')

In [104]:
df_rating = pd.read_csv('check.csv')
df_rating.sort_values('rating', ascending = False).head()

title  rating
2310           Shawshank Redemption, The (1994)     153
2092                        Pulp Fiction (1994)     123
956                         Forrest Gump (1994)     116
1660                         Matrix, The (1999)     109
2445  Star Wars: Episode IV - A New Hope (1977)     104

# Task4

In [106]:
df = pd.read_csv('power.csv')
df.head()

country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [107]:
df_filtered = df[(df['year']  >= 2005) & (df['year'] <= 2010) & (df['category'].isin(['4', '12', '21'])) 
                & (df['country'].isin(['Latvia', 'Estonia', 'Lithuania'])) & (df['quantity'] > 0)]
df_filtered.head()

country  year  quantity  category
10617    Estonia  2008       1.0         4
10620    Estonia  2005       1.0         4
11156  Lithuania  2008       1.0         4
11158  Lithuania  2006       1.0         4
11159  Lithuania  2005       1.0         4

In [108]:
sum_consumption = df_filtered['quantity'].sum()
print(sum_consumption)

240580.0


Ниже просто проверял, что все условия задания правильно учтены

In [109]:
df_filtered['category'].unique()

array([ 4, 12, 21])

# Task 5

In [110]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
x = np.linalg.solve(a, b)
print(x)
print(np.allclose(np.dot(a, x), b))

[ 0.46666667  3.84444444 -5.55555556]
True
